name: lyceum_entrance
background: bg.png
pass_map: pass.png
triggers:
    -   rect: [318, 573, 163, 19]
        events:
            enter: room::lyceum_pre
    -   rect: [325, 1, 159, 14]
        events:
            enter: room::lyceum_hall
initial_positions:
    lyceum_pre: [400, 532]
    lyceum_hall: [400, 83]
objects:
    - pos: [400, 150]
      texture: flate/overworld.png//2
      hitbox: [-60, -30, 120, 70]
      is_passable: false
      name: flate
      on_interact: python::flate_interact.py
      if: |
          return state['itt_test_tutorial'] == 'unmet'
