name: lyceum_entrance
background: bg.png
pass_map: pass.png
triggers:
    -   rect: [318, 573, 163, 19]
        events:
            enter: room::lyceum_pre
initial_positions:
    lyceum_pre: [400, 532]
scripts:
    on_load: python::spawn_flate.py
