name: lyceum_2_right
background: bg.png
pass_map: pass.png

triggers:
    - rect: [633, 260, 97, 10]
      events:
        enter: room::lyceum_staircase_r
    - rect: [481, 261, 85, 232]
      events:
        enter: |
            dynamic::
            if state['lyceum_2_right_fights']['algebroid']:
                return []
            return 'python::fight_algebroid@fights.py'

initial_positions:
    lyceum_staircase_r: [684, 315]

scripts: {}
objects: []
