name: lyceum_2_right
background: bg.png
pass_map: pass.png

triggers:
    - rect: [633, 260, 97, 10]
      events:
        enter: room::lyceum_staircase_r
    - rect: [0, 258, 25, 236]
      events:
        enter: room::lyceum_2_midright_1
    - rect: [481, 261, 85, 232]
      events:
        enter: |
            dynamic::
            if state['lyceum_2_right_fights']['algebroid']:
                return []
            return 'python::fight_algebroid@fights.py'
    - rect: [296, 262, 74, 230]
      events:
        enter: |
            dynamic::
            if state['lyceum_2_right_fights']['geoma']:
                return []
            return 'python::fight_geoma@fights.py'
    - rect: [114, 260, 70, 241]
      events:
        enter: |
            dynamic::
            if state['lyceum_2_right_fights']['literallia']:
                return []
            return 'python::fight_literallia@fights.py'

    - rect: [102, 122, 89, 141]
      events:
        interact: text::overworld/lyceum_2_right/door-closed

    - rect: [294, 123, 91, 140]
      events:
        interact: |
            dynamic::
            if state['unlocked_ruler']:
                return 'room::lyceum_2_geoma'
            else:
                return 'text::overworld/lyceum_2_right/door-closed-geoma'

    - rect: [478, 123, 93, 140]
      events:
        interact: text::overworld/lyceum_2_right/door-closed


initial_positions:
    lyceum_staircase_r: [684, 315]
    lyceum_2_midright_1: [66, 378]
    lyceum_2_geoma: [335, 340]

scripts: {}
objects: []
