name: lyceum_hall
background: bg.png
pass_map: pass.png
triggers:
    - rect: [553, 589, 130, 10]
      events:
        enter: room::lyceum_entrance
    - rect: [320, 224, 90, 29]
      events:
        interact: text::overworld/lyceum_hall/door
    - rect: [829, 233, 89, 25]
      events:
        interact: text::overworld/lyceum_hall/door
    - rect: [52, 217, 85, 34]
      events:
        interact: text::overworld/lyceum_hall/canteen
    - rect: [582, 231, 93, 29]
      events:
        interact: text::overworld/lyceum_hall/emblem

initial_positions:
    lyceum_entrance: [619, 493]
scripts: {}
save_point:
    pos: [787, 452]
    script: text::overworld/lyceum_hall/save
