name: lyceum_hall
background: bg.png
pass_map: pass.png
triggers:
    - rect: [553, 589, 130, 10]
      events:
        enter: room::lyceum_entrance
    - rect: [1178, 262, 21, 231]
      events:
        enter: room::lyceum_1_right
    - rect: [0, 258, 13, 236]
      events:
        enter: room::lyceum_1_canteen
    - rect: [320, 224, 90, 29]
      events:
        interact: text::overworld/lyceum_hall/door
    - rect: [829, 233, 89, 25]
      events:
        interact: text::overworld/lyceum_hall/door
    - rect: [52, 217, 85, 34]
      events:
        interact: text::overworld/lyceum_hall/canteen
    - rect: [582, 231, 93, 29]
      events:
        interact: text::overworld/lyceum_hall/emblem

objects:
    - pos: [0, 0]
      texture: grumpylook/overworld.png
      rect: [1115, 262, 31, 230]
      on_interact: text::overworld/lyceum_hall/grumpylook/first_met


initial_positions:
    lyceum_entrance: [619, 493]
    lyceum_1_right: [1107, 376]
    lyceum_1_canteen: [85, 383]

scripts: {}

save_point:
    pos: [787, 452]
    script: text::overworld/lyceum_hall/save
