name: lyceum_pre
background: bg.png
pass_map: pass.png
triggers:
    -   rect: [300, 585, 200, 15]
        events:
            enter: room::start
    -   rect: [335, 296, 111, 22]
        events:
            enter: room::lyceum_entrance
initial_positions:
    start: [400, 500]
    lyceum_entrance: [400, 361]
