name: lyceum_2_mid_1
background: bg.png
pass_map: pass.png


triggers:
    - rect: [1026, 672, 23, 127]
      events:
        enter: room::lyceum_2_midright_2
    - rect: [0, 37, 24, 174]
      events:
        enter: room::lyceum_2_mid_2


initial_positions:
    lyceum_2_midright_2: [993, 739]
    lyceum_2_mid_2: [57, 125]


scripts:
    on_load: python::spawn_madecs.py        
