name: lyceum_staircase_r
background: bg.png
pass_map: pass.png
triggers:
    - rect: [330, 1337, 184, 15]
      events:
        enter: room::lyceum_1_right
    - rect: [0, 991, 11, 121]
      events:
        enter: room::lyceum_2_right

initial_positions:
    lyceum_1_right: [422, 1285]
    lyceum_2_right: [53, 1049]
scripts: {}
objects:
    - pos: [0, 0]
      rect: [331, 829, 182, 155]
      texture: fence.png
      on_interact: text::overworld/lyceum_staircase_r/fence
      if: |
          return not state['lyceum_staircase_unlocked']
