name: lyceum_staircase_r
background: bg.png
pass_map: pass.png
triggers:
    - rect: [330, 1337, 184, 15]
      events:
        enter: room::lyceum_1_right
    - rect: [0, 991, 11, 121]
      events:
        enter: room::lyceum_2_right
    - rect: [331, 0, 182, 18]
      events:
        enter: room::lyceum_5_right

initial_positions:
    lyceum_1_right: [422, 1285]
    lyceum_2_right: [53, 1049]
    lyceum_5_right: [420, 40]
scripts: {}
objects:
    - pos: [0, 0]
      rect: [329, 834, 183, 138]
      texture: fence.png
      on_interact: text::overworld/lyceum_staircase_r/fence
      if: |
          return not state['lyceum_staircase_unlocked']
    - pos: [0, 0]
      rect: [329, 400, 183, 138]
      texture: fence.png
      on_interact: text::overworld/lyceum_staircase_r/fence_upper
      if: |
          return not state['lyceum_staircase_unlocked']
